var express = require('express');
var router = express.Router();

/* GET home page. */
const listItems = [
  {'id': '1 ','term': 'IaaS','description': 'IaaS is a category of cloud service that provides access to infrastructure resources, such as data storage, VMs or containers. When you use IaaS, you can quickly and easily deploy the infrastructure you need to host applications or store data in the cloud','references': 'https://www.techtarget.com/searchcloudcomputing/feature/How-to-choose-a-PaaS-or-IaaS-that-aligns-with-DevOps#:~:text=What%20are%20the%20benefits%20of%20IaaS%20for%20DevOps%3F,store%20data%20in%20the%20cloud'},
  {'id': '2','term': 'Application Deployment','description': 'Deployment in DevOps is a process that enables you to retrieve important codes from version control so that they can be made readily available to the public and they can use the application in a ready-to-use and automated fashion.','references': 'https://www.knowledgehut.com/blog/devops/devops-deployment-tools'},
  {'id': '3','term': 'Application Servers','description': 'Application servers provide the core functionality of the WebSphere® Application Server product family. Application servers extend the ability of a web server to handle Web application requests, and much more. An application server enables a server to generate a dynamic, customized response to a client request.','references': 'https://www.ibm.com/docs/en/was/9.0.5?topic=administering-introduction-application-servers'},
  {'id': '4','term': 'Behavior-Driven Development Testing','description': 'BDD (behavior-driven development) is a software development process based on the Agile methodology. The concept of behavior-driven development originated from the test-driven development (TDD) approach. This software development process is focused on end-user requirements and their interactions with the product.','references': 'https://www.spiceworks.com/tech/devops/articles/what-is-bdd/#:~:text=BDD%20(behavior%2Ddriven%20development),their%20interactions%20with%20the%20product.'},
  {'id': '5','term': 'Code Inspection / Code Quality','description': 'Code quality refers to how well-written and maintainable software code is. It encompasses factors such as readability, efficiency, scalability, reliability, maintainability and security. High code quality ensures that software is easy to understand, modify and extend, has fewer bugs and is less likely to break down.','references': 'https://devops.com/5-unusual-ways-to-improve-code-quality/#:~:text=Code%20quality%20refers%20to%20how,less%20likely%20to%20break%20down.'},
  {'id': '6','term': 'Configuration Management','description': 'Configuration management occurs when a configuration platform is used to automate, monitor, design and manage otherwise manual configuration processes. System-wide changes take place across servers and networks, storage, applications, and other managed systems','references': 'https://www.bmc.com/blogs/devops-configuration-management'},
  {'id': '7','term': 'Containerization Tools','description': 'Containerization packages software code with dependencies and an operating system in the form of a standalone application that can be run on top of another computer. These virtualized environments are lightweight by design and require comparatively little computing power. They can also be run on any underlying infrastructure and are portable, or are able to be consistently run on any platform.','references': 'https://resources.github.com/devops/containerization/'},
  {'id': '8','term': 'Continuous Integration & Deployment','description': 'CI stands for continuous integration, a fundamental DevOps best practice where developers frequently merge code changes into a central repository where automated builds and tests run. But CD can either mean continuous delivery or continuous deployment','references': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment#:~:text=CI%20stands%20for%20continuous%20integration,continuous%20delivery%20or%20continuous%20deployment.'},
  {'id': '9','term': 'Web servers','description': 'Web server is a computer where the web content is stored. Basically web server is used to host the web sites but there exist other web servers also such as gaming, storage, FTP, email etc. A web server stores and delivers the content for a website – such as text, images, video, and application data – to clients that request it.','references': 'https://www.devopsschool.com/blog/list-of-top-5-web-servers-in-2021/#:~:text=A%20web%20server%20stores%20and,to%20clients%20that%20request%20it.'},
  {'id': '10','term': 'Version Control / Branch Management','description': 'Branching is the process of creating separate branches of code that developers work on. After the branch code has been tested and the work is finished, the branch gets migrated to the trunk of the code.','references': 'https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'},
  {'id': '11','term':'Issue Tracking','description':'A procedure that enables programmers and quality control staff to follow the progression of new features and errors from identification to resolution.','references':'https://learn.microsoft.com/en-us/azure/well-architected/devops/issue-tracking'},
  {'id': '12','term':'Rollback','description':'The simplest approach to reverse a deployment is to use deployment rollback. It entails reverting your programme to a prior version using a backup or a source control repository.','references':'https://www.linkedin.com/advice/0/how-do-you-choose-between-deployment-rollback'},
  {'id': '13','term':'Elasticity','description':'Elasticity refers to the capacity to dynamically scale computer resources up or down in response to demand. Utilising containerization or cloud infrastructure technologies, it includes real-time resource allocation and deallocation to provide optimal performance and cost effectiveness in response to shifting workloads.','references':'https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-elastic-computing'},
  {'id': '14','term':'Infrastructure as Code(IaC)','description':'Infrastructure as Code refers to the delivery and management of infrastructure using code as opposed to manual procedures.','references':'https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac#:~:text=Infrastructure%20as%20Code%20(IaC)%20is,to%20edit%20and%20distribute%20configurations.'},
  {'id': '15','term':'Infrastructure Monitoring','description':'Infrastructure monitoring involves gathering and analysing data from IT systems, processes, and infrastructure in order to enhance business outcomes and provide value for the entire organisation.','references':'https://www.dynatrace.com/news/blog/what-is-infrastructure-monitoring-2/#:~:text=Infrastructure%20monitoring%20is%20the%20process,the%20oxygen%20to%20your%20infrastructure.'},
  {'id': '16','term':'Microservices','description':'The architectural method of creating a distributed application using independently deployable services that carry out certain business operations and interact via web interfaces is known as microservices.','references':'https://learn.microsoft.com/en-us/devops/deliver/what-are-microservices'},
  {'id': '17','term':'Quality Assurance(QA)','description':'Testing in real-time helps developers by simplifying the product pipeline by doing ongoing quality checks to keep the testing cycle operating smoothly.','references':'https://www.copado.com/devops-hub/blog/dont-underestimate-the-role-of-qa-in-devops-for-these-3-reasons-crt'},
  {'id': '18','term':'Workflow','description':'The sequence in which tasks are executed is referred to as the workflow.','references':'https://hkrtrainings.com/devops-workflow'},
  {'id': '19','term':'Container registry','description':'A repository, or group of repositories, is used to store and provide access to container images.','references':'https://www.redhat.com/en/topics/cloud-native-apps/what-is-a-container-registry#:~:text=A%20container%20registry%20is%20a,as%20part%20of%20DevOps%20processes'},
  {'id': '20','term':'Docker','description':'The best technology for creating and executing containers is offered by Docker. All significant operating systems support the open source, industry-standard Docker format, or OCI.','references':'https://kodekloud.com/blog/role-of-docker-in-devops/#'},
  {'id': '21','term':'Internal developer platform (IDP)','description':'An Internal Developer Platform within the realm of DevOps denotes a collection of tools, services, and methodologies aimed at optimizing and augmenting the software development procedure within a company. This framework serves as an environment granting development teams the autonomy to independently initiate, launch, and oversee applications, all while achieving heightened swiftness and effectiveness.','references':'https://thechief.io/c/editorial/what-is-an-internal-developer-platform/'},
  {'id': '22','term':'Rolling deployments','description':'Rolling deployments within the DevOps context entail a deployment approach wherein fresh iterations of an application or software are progressively and consecutively launched into the production environment. Instead of implementing the new version in its entirety simultaneously, this approach revolves around gradually enhancing specific portions of the infrastructure while maintaining the current versions operation.','references':'https://www.techtarget.com/searchitoperations/definition/rolling-deployment'},
  {'id': '23','term':'Runbooks','description':'Runbooks within the context of DevOps comprise documented protocols, directions, and principles that furnish a methodical, stepwise methodology for overseeing, resolving issues, and upholding systems, applications, and procedures.','references':'https://www.blameless.com/blog/runbook-template-devops'},
  {'id': '24','term':'Capacity Test','description':'The objective of a capacity test is to ascertain the highest workload the system can manage prior to encountering reduced performance or system failure.','references':'https://www.radview.com/blog/all-you-need-to-know-about-capacity-testing/#:~:text=Capacity%20Testing%20exercises%20the%20system,the%20infrastructure%20to%20optimize%20quality.'},
  {'id': '25','term':'Exploratory Testing','description':'Exploratory testing entails a flexible and spontaneous testing method where testers engage with the software by actively exploring its functionalities. They do so without depending on preplanned test cases. This process involves learning about the system, uncovering problems, and spontaneously devising test scenarios.','references':'https://www.guru99.com/exploratory-testing.html'},
  {'id': '26','term':'Mean Time Between Failures (MTBF)','description':'Mean Time Between Failures (MTBF) serves as a measurement that calculates the average duration a software application or system functions before facing a failure. This metric is employed to assess the dependability and consistency of the application within an environment focused on continuous delivery and deployment.','references':'https://medium.com/@fabiojose/devops-kpi-chapter-3-3f47fcec9673'},
  {'id': '27','term':'User Acceptance Test','description':'User Acceptance Testing (UAT) constitutes a stage within the software development lifecycle in which the application or system undergoes assessment by end-users or stakeholders. The aim is to confirm that the software aligns with their needs and anticipated outcomes. UATs purpose is to ascertain whether the software is prepared for release and deployment, guided by user requirements.','references':'https://devops.com/what-is-user-acceptance-testing-and-why-is-it-so-important/'},
  {'id': '28','term':'Fail Fast','description':'The principle underscores the importance of promptly recognizing and rectifying failures in the early stages of the software development process. It promotes swift identification and resolution of problems to prevent their escalation to later phases or production environments.','references':'https://katalon.com/resources-center/blog/stop-test-execution-fail-fast'},
  {'id': '29','term':'Release Orchestration','description':'Release orchestration involves strategically coordinating and overseeing the complete release lifecycle of software applications or systems. This encompasses planning, automation, and overseeing the deployment of new enhancements, updates, or features across different environments, spanning from development to production.','references':'https://www.professional-devops.com/release-orchestration.html'},
  {'id': '30','term':'Datadog','description':'Datadog serves as a monitoring and analytics platform utilized for obtaining valuable insights into the performance, availability, and overall well-being of applications, infrastructure, and systems. Its comprehensive set of tools and features is tailored to support teams in effectively monitoring, identifying and resolving issues, as well as enhancing the efficiency of their environments.','references':'https://petri.com/what-is-datadog/'},
  {'id': '31','term':'Cluster','description':'In DevOps, clusters represent networks of interconnected servers or nodes intentionally set up to improve the accessibility, expandability, efficiency, and failover capabilities of applications and services. They form a crucial component in contemporary approaches to managing infrastructure and applications.','references':'https://octopus.com/blog/new-devops-performance-clusters#:~:text=A%20cluster%20is%20a%20group,be%20arranged%20methodically%20for%20comparison.'},
  {'id': '32','term':'Mean Time to Recovery(MTTR)','description':'MTTR in DevOps represents the average duration for a system or application to bounce back after encountering a failure or incident. It serves as a crucial measure for DevOps teams to gauge their proficiency in promptly addressing and resolving problems.','references':'https://www.atlassian.com/incident-management/kpis/common-metrics.'},
  {'id': '33','term':'Staging Environment','description':'A staging environment is a controlled and distinct setup that replicates the production environment, serving as a testing ground for code modifications, updates, or new features to be thoroughly examined and validated before being rolled out to the real production environment.','references':'https://www.quali.com/blog/how-to-manage-staging-environments-to-speed-up-devops/#:~:text=The%20product%20team%20commonly%20employs,other%20testing%20systems%20run%20smoothly.'},
  {'id': '34','term':'White Box Testing','description':'White box testing involves scrutinizing the internal architecture, code, and operational logic of a software application. This method, also referred to as "clear box testing" or "glass box testing," grants testers access to the source code and an understanding of the software inner workings.','references':'https://www.geeksforgeeks.org/software-engineering-white-box-testing/'},
  {'id': '35','term':'GitHub','description':'GitHub plays a pivotal role in DevOps methodologies, functioning as a hub for version management, team cooperation, automation, and the establishment of CI/CD pipelines. It holds a central position in contemporary software development and deployment processes.','references':'https://www.predicagroup.com/blog/devops-github-guide/'},
  {'id': '36','term':'Kubernetes','description':'Kubernetes plays a vital role in DevOps by facilitating container orchestration, scalability, ensuring high availability, automating tasks, and advocating for the use of infrastructure as code principles. It boosts the pace, dependability, and uniformity of software deployments, all in accordance with the fundamental tenets of DevOps.','references':'https://www.turing.com/blog/importance-of-kubernetes-for-devops/'},
  {'id': '37','term':'Terraform','description':'Terraform serves as a potent asset within the DevOps arsenal, allowing for the control of infrastructure through code, the automation of provisioning, compatibility with multi-cloud setups, seamless integration with CI/CD pipelines, and the advocacy of robust and replicable infrastructure modifications. It is pivotal in establishing both the flexibility and uniformity of infrastructure within DevOps workflows.','references':'https://www.scaler.com/topics/devops-tutorial/what-is-terraform/'},
  {'id': '38','term':'RabbitMQ','description':'RabbitMQ, functioning as a message broker, improves communication, scalability, and dependability within DevOps methodologies. It encourages the separation of components, enables event-driven structures, and facilitates seamless integration across different phases of the software development and deployment process.','references':'https://blog.devops.dev/what-is-rabbitmq-a1aca953d4c1'},
  {'id': '39','term':'Quality Assurance(QA)','description':'Quality assurance encompasses a comprehensive strategy aimed at guaranteeing that software adheres to quality benchmarks throughout the entire development and deployment process. It involves the fusion of testing, automation, security measures, and collaborative efforts to consistently and efficiently produce top-notch software.','references':'https://www.browserstack.com/guide/role-of-qa-in-devops'},
  {'id': '40','term':'Pipeline','description':'Pipeline denotes a sequence of automated phases that code and modifications undergo, commencing from development and concluding with deployment. This automated system optimizes and simplifies the procedure of constructing, testing, and distributing software, enhancing effectiveness and dependability in software development and distribution. Essential elements of a DevOps pipeline typically encompass code merging, testing, release, and monitoring.','references':'https://www.atlassian.com/devops/devops-tools/devops-pipeline#:~:text=A%20DevOps%20pipeline%20is%20a,code%20to%20a%20production%20environment.'},
  {'id': '41','term':'Release management','description':'Release management withintherealmof DevOpsplaysa vitalrolein meticulously orchestrating, scheduling,and overseeingthe softwarerelease procedureto guaranteethe effectiveand dependable distributionof softwareupdates orfresh functionalities.','references':'https://www.bunnyshell.com/blog/what-is-release-man agement/'},
  {'id': '42','term':'Complex-Adaptive System (CAS)','description':'complexadaptive systemrefersto thedynamicand intricatenatureof thesoftware developmentand deliveryprocess, wherevarious interconnected components, teams,and processes continuously adapttochanges andevolveover time.','references':'https://www.agilethinkers.academy/what-is-complex-a daptive-system'},
  {'id': '43','term':'Functional Testing','description':'Functional testing within the context of DevOps plays a pivotal role in the software testing procedure by concentrating on confirming that an application functionalities and attributes operate as planned. Its purpose is to ascertain that the software adheres to the designated functional criteria and delivers an acceptable user experience.','references':'https://www.microfocus.com/en-us/what-is/functional-testing#:~:text=Related%20Products-,Overview,with%20'},
  {'id': '44','term':'Pair Programming','description':'Pair programming within the DevOps framework nurtures teamwork, the exchange of knowledge, and code excellence, all of which are vital for the efficient delivery of dependable software. It synergizes effectively with the fundamental DevOps tenets of automation, collaboration, and a holistic approach to the software delivery process.','references':'https://www.techtarget.com/searchsoftwarequality/definition/Pair-programming#:~:text=Pair%20programming%20is%20a%20collaborative,well%20suited%20for%20everyone%2C%20however.'},
  {'id': '45','term':'Private Cloud','description':'Private cloud in DevOps offers control, security, scalability, and customization, making it a valuable choice for organizations that prioritize data privacy, compliance, and tailored infrastructure solutions. It enables DevOps teams to build and deploy applications with confidence while adhering to their specific requirements and practices.','references':'https://www.ibm.com/topics/private-cloud'},
  {'id': '46','term':'Lead Time','description':'Assessing lead time within DevOps is crucial as it helps pinpoint obstacles, inefficiencies, and opportunities for enhancement in the software development and delivery process. A prevalent objective in DevOps is to reduce lead times, facilitate swifter and more adaptable development cycles, minimize resource wastage, and boost overall agility.','references':'https://www.software.com/devops-guides/lead-time'},
  {'id': '47','term':'Backup','description':'Backup is an integral part of ensuring data availability and system resilience in DevOps. It helps mitigate the risks associated with data loss and system failures, supporting the continuous delivery and reliability of software systems.','references':'https://www.cncf.io/blog/2023/03/30/devops-backup-use-case-how-to-build-a-backup-strategy-for-github-gitlab-bitbucket-or-jira-data/'},
  {'id': '48','term':'Regression Testing','description':'Regression testing is a critical component of DevOps as it ensures the stability and reliability of software throughout the continuous integration and continuous deployment process. By automating and integrating regression testing into the DevOps pipeline, teams can catch and fix issues early, reducing the risk of regressions and delivering high-quality software to users.','references':'https://katalon.com/resources-center/blog/regression-testing'},
  {'id': '49','term':'Agile','description':'Agile integration represents the seamless blending of Agile methods with DevOps approaches, enabling software development teams to effectively and swiftly provide customer-centric, top-notch software. This integration places a significant emphasis on teamwork, automation, and ongoing enhancement across the entire software delivery cycle.','references':'https://www.atlassian.com/devops/what-is-devops/agile-vs-devops#:~:text=Agile%20emphasizes%20collaboration%20between%20developers,focus%20to%20delivery%20and%20maintenance'},
  {'id': '50','term':'Incident Management','description':'Managing incidents plays a crucial role in upholding system dependability and reducing service disruptions. It promotes a proactive stance toward preventing incidents and cultivates a culture of ongoing learning and enhancement. Through the swift resolution of issues and comprehensive post-incident assessments, DevOps teams strive to bolster system resilience and elevate customer satisfaction.','references':'https://www.atlassian.com/incident-management/devops'}
];

router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary',
  list: listItems });
});

module.exports = router;
