var express = require('express');
var router = express.Router();

/* GET home page. */
const listItems = [
  {'id': '1 ','term': 'IaaS','description': 'IaaS is a category of cloud service that provides access to infrastructure resources, such as data storage, VMs or containers. When you use IaaS, you can quickly and easily deploy the infrastructure you need to host applications or store data in the cloud','references': 'https://www.techtarget.com/searchcloudcomputing/feature/How-to-choose-a-PaaS-or-IaaS-that-aligns-with-DevOps#:~:text=What%20are%20the%20benefits%20of%20IaaS%20for%20DevOps%3F,store%20data%20in%20the%20cloud'},
  {'id': '2','term': 'Application Deployment','description': 'Deployment in DevOps is a process that enables you to retrieve important codes from version control so that they can be made readily available to the public and they can use the application in a ready-to-use and automated fashion.','references': 'https://www.knowledgehut.com/blog/devops/devops-deployment-tools'},
  {'id': '3','term': 'Application Servers','description': 'Application servers provide the core functionality of the WebSphere® Application Server product family. Application servers extend the ability of a web server to handle Web application requests, and much more. An application server enables a server to generate a dynamic, customized response to a client request.','references': 'https://www.ibm.com/docs/en/was/9.0.5?topic=administering-introduction-application-servers'},
  {'id': '4','term': 'Behavior-Driven Development Testing','description': 'BDD (behavior-driven development) is a software development process based on the Agile methodology. The concept of behavior-driven development originated from the test-driven development (TDD) approach. This software development process is focused on end-user requirements and their interactions with the product.','references': 'https://www.spiceworks.com/tech/devops/articles/what-is-bdd/#:~:text=BDD%20(behavior%2Ddriven%20development),their%20interactions%20with%20the%20product.'},
  {'id': '5','term': 'Code Inspection / Code Quality','description': 'Code quality refers to how well-written and maintainable software code is. It encompasses factors such as readability, efficiency, scalability, reliability, maintainability and security. High code quality ensures that software is easy to understand, modify and extend, has fewer bugs and is less likely to break down.','references': 'https://devops.com/5-unusual-ways-to-improve-code-quality/#:~:text=Code%20quality%20refers%20to%20how,less%20likely%20to%20break%20down.'},
  {'id': '6','term': 'Configuration Management','description': 'Configuration management occurs when a configuration platform is used to automate, monitor, design and manage otherwise manual configuration processes. System-wide changes take place across servers and networks, storage, applications, and other managed systems','references': 'https://www.bmc.com/blogs/devops-configuration-management'},
  {'id': '7','term': 'Containerization Tools','description': 'Containerization packages software code with dependencies and an operating system in the form of a standalone application that can be run on top of another computer. These virtualized environments are lightweight by design and require comparatively little computing power. They can also be run on any underlying infrastructure and are portable, or are able to be consistently run on any platform.','references': 'https://resources.github.com/devops/containerization/'},
  {'id': '8','term': 'Continuous Integration & Deployment','description': 'CI stands for continuous integration, a fundamental DevOps best practice where developers frequently merge code changes into a central repository where automated builds and tests run. But CD can either mean continuous delivery or continuous deployment','references': 'https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment#:~:text=CI%20stands%20for%20continuous%20integration,continuous%20delivery%20or%20continuous%20deployment.'},
  {'id': '9','term': 'Web servers','description': 'Web server is a computer where the web content is stored. Basically web server is used to host the web sites but there exist other web servers also such as gaming, storage, FTP, email etc. A web server stores and delivers the content for a website – such as text, images, video, and application data – to clients that request it.','references': 'https://www.devopsschool.com/blog/list-of-top-5-web-servers-in-2021/#:~:text=A%20web%20server%20stores%20and,to%20clients%20that%20request%20it.'},
  {'id': '10','term': 'Version Control / Branch Management','description': 'Branching is the process of creating separate branches of code that developers work on. After the branch code has been tested and the work is finished, the branch gets migrated to the trunk of the code.','references': 'https://www.heptabit.at/blog/devops/devops-branching-strategy-what-is-it-how-it-works#:~:text=Branching%20is%20the%20process%20of,be%20complicated%20and%20get%20messy.'}
];

router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary',
  list: listItems });
});

module.exports = router;
